# --- PROJECT CONFIGURATION --- #

# Metadata (see https://peps.python.org/pep-0621/)
[project]
name = "ocf-dataservices"
version = "0.1.0"
description = "Pipelines for the ingestion and conversion of data relevant to OCF's workloads."
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.14"
license = {text = "MIT License"}
authors = [
    { name = "Open Climate Fix Team", email = "info@openclimatefix.org"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "dagster>=1.12.11",
    "dagster-aws>=0.28.11",
    "dagster-postgres>=0.28.11",
    "dagster-webserver>=1.12.11",
    "icechunk>=2.1.1",
    "requests>=2.31.0",
    "sentry-sdk>=2.66,<3",
    "ecmwfmars-data",
    "dynamical-data",
    "schemas",
    "ecmwflive-data",
    "pandera>=0.32.1",
    "xarray>=2026.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "dagster-dg-cli",
    "ruff>=0.14.13",
    "ty>=0.0.16",
    "unittest-xml-reporting>=4.0.0",
    "moto[server]>=5.0.0",
]

[project.urls]
repository = "https://github.com/openclimatefix/ocf-dataservices"

# --- UV WORKSPACE CONFIG ---
# See: https://docs.astral.sh/uv/concepts/projects/workspaces

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
ecmwfmars-data = { workspace = true }
dynamical-data = { workspace = true }
schemas = { workspace = true }
ecmwflive-data = { workspace = true }


[tool.hatch.build.targets.wheel]
packages = ["src/ocf_dataservices"]

# --- DAGSTER ---

[tool.dagster]
module_name = "ocf_dataservices.definitions"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "ocf_dataservices"
registry_modules = [
    "ocf_dataservices.components.*",
]

# --- LINTING AND TYPING CONFIGURATION --- #

# Ruff configuration
# See https://docs.astral.sh/ruff/configuration/
[tool.ruff]
line-length = 100

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 100
