import shutil
from pathlib import Path

import dagster as dg


class RawFileIOManager(dg.ConfigurableIOManager):
    base_path: str = ""

    def _get_path(self, context: dg.OutputContext | dg.InputContext) -> Path:
        """Construct the storage path based on the asset key and partition."""
        keys = context.asset_key.path

        # e.g. /tmp/dagster_storage/l0/nwp/ecmwf_mars_ens.../
        dir_path = Path(self.base_path).joinpath(*keys)

        if context.has_partition_key:
            partition_key = context.partition_key
            year = (
                partition_key[:4]
                if len(partition_key) >= 4 and partition_key[:4].isdigit()
                else "unknown"
            )
            # Colons are difficult characters for filenames across file systems (e.g. Windows)
            # but we preserve them here if the string natively includes it,
            # or optionally sanitize it: safe_key = partition_key.replace(":", "")
            return dir_path / year / f"{partition_key}.grib"
        else:
            return dir_path / "data.grib"

    def handle_output(self, context: dg.OutputContext, obj: Path | str) -> None:
        """Move the temporary file generated by the asset to the final L0 storage location."""
        if not isinstance(obj, (Path, str)):
            raise dg.DagsterInvariantViolationError(
                f"RawFileIOManager expects a file path (Path or str), got {type(obj)}"
            )

        source_path = Path(obj)
        if not source_path.exists():
            raise FileNotFoundError(f"Source file does not exist: {source_path}")

        target_path = self._get_path(context)
        target_path.parent.mkdir(parents=True, exist_ok=True)

        context.log.info(f"Moving L0 data from {source_path} to {target_path}")
        shutil.move(source_path, target_path)

        size_bytes = target_path.stat().st_size
        context.add_output_metadata(
            {
                "storage_path": dg.MetadataValue.path(str(target_path)),
                "size_bytes": dg.MetadataValue.int(size_bytes),
                "size_human_readable": dg.MetadataValue.text(
                    f"{size_bytes / (1024 * 1024):.2f} MB"
                ),
            }
        )

    def load_input(self, context: dg.InputContext) -> Path:
        """Return the path to the stored L0 file for the downstream asset to read."""
        target_path = self._get_path(context)

        if not target_path.exists():
            raise FileNotFoundError(f"Required L0 input file not found: {target_path}")

        context.log.info(f"Loading L0 data from {target_path}")
        return target_path
